from collections.abc import Awaitable, Coroutine
from typing import Any, TypeVar

_T = TypeVar("_T")

async def sleep(seconds: float) -> None: ...
async def sleep_ms(milliseconds: int) -> None: ...
def create_task(coro: Coroutine[Any, Any, _T]) -> Any: ...
def run(coro: Awaitable[_T]) -> _T: ...
