from typing import Any

def time() -> float: ...
def sleep(seconds: float) -> None: ...
def sleep_ms(milliseconds: int) -> None: ...
def ticks_ms() -> int: ...
def ticks_diff(new: int, old: int) -> int: ...
def gmtime(seconds: float | None = None) -> tuple[int, int, int, int, int, int, int, int]: ...
